services:
  #сервер конфигурации
  configSrv:
    image: mongo:latest # docker образ
    container_name: configSrv 
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    command:
      [
        "--configsvr",  #запуск в режиме конфигурации
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #1-й шард с репликами
  shard1-1:
    image: mongo:latest # docker образ
    container_name: shard1-1
    restart: always
    ports:
      - "27018:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.9
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet",
        "shard1-1", #название реплики
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-1secondary1:
    image: mongo:latest # docker образ
    container_name: shard1-1replica1
    command: --shardsvr --replSet shard1-1 --port 27028
    ports:
      - 27028:27028
    networks:
      app-network:
        ipv4_address: 173.17.0.11

  shard1-1secondary2:
    image: mongo:latest # docker образ
    container_name: shard1-1replica2
    command: --shardsvr --replSet shard1-1 --port 27038
    ports:
      - 27038:27038
    networks:
      app-network:
        ipv4_address: 173.17.0.12

  shard1-1secondary3:
    image: mongo:latest # docker образ
    container_name: shard1-1replica3
    command: --shardsvr --replSet shard1-1 --port 27048
    ports:
      - 27048:27048
    networks:
      app-network:
        ipv4_address: 173.17.0.13

  #2-й шард 
  shard1-2:
    image: mongo:latest # docker образ
    container_name: shard1-2
    restart: always
    ports:
      - "27019:27019"
    networks:
      app-network:
        ipv4_address: 173.17.0.8
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet",
        "shard1-2replica", #название реплик
        "--bind_ip_all", # обратите внимание - она отличается от реплики 1-го шарда
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  
  shard1-2secondary1:
    image: mongo:latest # docker образ
    container_name: shard1-2secondary1
    command: --shardsvr --replSet shard1-2replica --port 27029
    ports:
      - 27029:27029
    networks:
      app-network:
        ipv4_address: 173.17.0.14

  shard1-2secondary2:
    image: mongo:latest # docker образ
    container_name: shard1-2secondary2
    command: --shardsvr --replSet shard1-2replica --port 27039
    ports:
      - 27039:27039
    networks:
      app-network:
        ipv4_address: 173.17.0.15
  
  shard1-2secondary3:
    image: mongo:latest # docker образ
    container_name: shard1-2secondary3
    command: --shardsvr --replSet shard1-2replica --port 27049
    ports:
      - 27049:27049
    networks:
      app-network:
        ipv4_address: 173.17.0.16

  #роутер
  mongos_router:
    image: mongo:latest # docker образ
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    command:
      [
        "mongos", #обычная mongo в режиме роутера
        "--configdb", 
        "config_server/configSrv:27017", #передача данных сервера конфигурации
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  
  #API
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
    ports:
      - 8085:8085
    environment:
      MONGODB_URL: "mongos_router://mongodb"
      MONGODB_DATABASE_NAME: "somedb"

  redis_1:
    image: "redis:latest"
    container_name: redis_1
    ports:
      - "6379"
    volumes:
      - redis_1_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.2

  redis_2:
    image: "redis:latest"
    container_name: redis_2
    ports:
      - "6379"
    volumes:
      - redis_2_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.3

  redis_3:
    image: "redis:latest"
    container_name: redis_3
    ports:
      - "6379"
    volumes:
      - redis_3_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.4

  redis_4:
    image: "redis:latest"
    container_name: redis_4
    ports:
      - "6379"
    volumes:
      - redis_4_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.5

  redis_5:
    image: "redis:latest"
    container_name: redis_5
    ports:
      - "6379"
    volumes:
      - redis_5_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.6

  redis_6:
    image: "redis:latest"
    container_name: redis_6
    ports:
      - "6379"
    volumes:
      - redis_6_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.7

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/24

volumes:
  mongodb1_data_container:
  redis_1_data: {}
  redis_2_data: {}
  redis_3_data: {}
  redis_4_data: {}
  redis_5_data: {}
  redis_6_data: {}